services:
  nginx:
    image: nginx:alpine
    container_name: magictravel_nginx
    ports:
      - "8080:80"
    volumes:
      # CAMBIO: Apuntar a la nueva ubicación del proyecto Laravel
      - ./magic/backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - magictravel_network
    restart: unless-stopped

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: magictravel_php
    volumes:
      # CAMBIO: Apuntar a la nueva ubicación del proyecto Laravel
      - ./magic/backend:/var/www/html
    environment:
      - APP_ENV=production # Cambiado a 'production' para entorno de producción
      - APP_DEBUG=false # Cambiado a 'false' para entorno de producción
      - DB_HOST=mysql
      - DB_DATABASE=magictravel_v_2
      - MYSQL_USER=mt_app
      - MYSQL_PASSWORD=MagicTravel_2025!
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis # Agregar esta línea
      - SESSION_DRIVER=redis # Agregar esta línea
    depends_on:
      - mysql
      - redis
    networks:
      - magictravel_network
    restart: unless-stopped

  mysql:
    image: mariadb:10.11
    container_name: magictravel_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_secure_2025
      - MYSQL_DATABASE=magictravel_v_2
      - MYSQL_USER=mt_app
      - MYSQL_PASSWORD=MagicTravel_2025!
    volumes:
      - mysql_data:/var/lib/mysql
    command: --innodb-buffer-pool-size=512M --query-cache-size=64M --query-cache-type=ON
    networks:
      - magictravel_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: magictravel_phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=mt_app
      - PMA_PASSWORD=MagicTravel_2025!
      - MYSQL_ROOT_PASSWORD=root_secure_2025
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    networks:
      - magictravel_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: magictravel_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - magictravel_network
    restart: unless-stopped

networks:
  magictravel_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
